---
title: "Correlations between overall intercept and varying intercept"
date: 2021-09-23
tags: ["R","Stan","SBC"]
draft: TRUE
---



```{r}
library(cmdstanr)
library(bayesplot)
options(mc.cores = parallel::detectCores())
```

```{r}
set.seed(24555202)
N <- 10
N_groups <- 5
groups <- rep(1:N_groups, length.out = N)
group_sd <- abs(rnorm(1))
group_r <- rnorm(N_groups, sd = group_sd)

intercept <- rnorm(1, mean = 5, sd = 2) 
mu <- intercept + group_r[groups]
y <- rpois(N, exp(mu))

data_stan <- list(N = N,
                  N_groups = N_groups,
                  groups = groups,
                  y = y)
```

## Non-centered

```{r}
model_code_nc <- "
data {
  int<lower=0> N;
  int<lower=1> N_groups;
  int<lower=1,upper=N_groups> groups[N];
  int<lower=0> y[N];
}

parameters {
  real intercept;
  vector[N_groups] group_z; 
  real<lower=0> group_sd;
}

transformed parameters {
  vector[N_groups] group_r = group_z * group_sd;
}

model {
  intercept ~ normal(5, 2);
  group_z ~ std_normal();
  group_sd ~ normal(0, 1);
  y ~ poisson_log(intercept + group_r[groups]);
}

"

model_nc <- cmdstan_model(write_stan_file(model_code_nc))
```
```{r}
fit_nc <- model_nc$sample(data = data_stan, refresh = 1000)
```

```{r}
mcmc_pairs(fit_nc$draws(), pars = c("group_sd", "intercept"), regex_pars = "group_z", np = nuts_params(fit_nc), transformations = list("group_sd" = "log"))
```

## Centered

```{r}
fit_nc$summary()
```

```{r}
model_code_c <- "
data {
  int<lower=0> N;
  int<lower=1> N_groups;
  int<lower=1,upper=N_groups> groups[N];
  int<lower=0> y[N];
}

parameters {
  real intercept;
  vector[N_groups] group_r; 
  real<lower=0> group_sd;
}

model {
  intercept ~ normal(5, 2);
  group_r ~ normal(0, group_sd);
  group_sd ~ normal(0, 1);
  y ~ poisson_log(intercept + group_r[groups]);
}

"

model_c <- cmdstan_model(write_stan_file(model_code_c))
```
```{r}
fit_c <- model_c$sample(data = data_stan, refresh = 1000)
```
```{r}
fit_c$summary()
```

```{r}
mcmc_pairs(fit_c$draws(), pars = c("group_sd", "intercept"), regex_pars = "group_r", np = nuts_params(fit_c), transformations = list("group_sd" = "log"))
```

## Centered - sum to zero

```{r}
model_code_c_sz <- "
functions {
  vector Q_sum_to_zero_QR(int N) {
    vector [2*N] Q_r;

    for(i in 1:N) {
      Q_r[i] = -sqrt((N-i)/(N-i+1.0));
      Q_r[i+N] = inv_sqrt((N-i) * (N-i+1));
    }
    Q_r = Q_r * inv_sqrt(1 - inv(N));
    return Q_r;
  }

  vector sum_to_zero_QR(vector x_raw, vector Q_r) {
    int N = num_elements(x_raw) + 1;
    vector [N] x;
    real x_aux = 0;

    for(i in 1:N-1){
      x[i] = x_aux + x_raw[i] * Q_r[i];
      x_aux = x_aux + x_raw[i] * Q_r[i+N];
    }
    x[N] = x_aux;
    return x;
  }
}

data {
  int<lower=0> N;
  int<lower=1> N_groups;
  int<lower=1,upper=N_groups> groups[N];
  int<lower=0> y[N];
}

transformed data {
  vector[2 * N_groups] groups_Q_r = Q_sum_to_zero_QR(N_groups);
}

parameters {
  real intercept;
  vector[N_groups - 1] group_r_raw; 
  real<lower=0> group_sd;
}

transformed parameters {
  vector[N_groups] group_r = sum_to_zero_QR(group_r_raw, groups_Q_r);
}

model {
  intercept ~ normal(5, 2);
  group_r_raw ~ normal(0, group_sd);
  group_sd ~ normal(0, 1);
  y ~ poisson_log(intercept + group_r[groups]);
}

"

model_c_sz <- cmdstan_model(write_stan_file(model_code_c_sz))
```
```{r}
fit_c_sz <- model_c_sz$sample(data = data_stan)
```
```{r}
fit_c_sz$summary()
```

```{r}
mcmc_pairs(fit_c_sz$draws(), pars = c("group_sd", "intercept"), regex_pars = "group_r_raw", np = nuts_params(fit_c_sz),
           transformations = list("group_sd" = "log"))
```

## Non-centered sum to zero

## Centered - sum to zero

```{r}
model_code_nc_sz <- "
functions {
  vector Q_sum_to_zero_QR(int N) {
    vector [2*N] Q_r;

    for(i in 1:N) {
      Q_r[i] = -sqrt((N-i)/(N-i+1.0));
      Q_r[i+N] = inv_sqrt((N-i) * (N-i+1));
    }
    Q_r = Q_r * inv_sqrt(1 - inv(N));
    return Q_r;
  }

  vector sum_to_zero_QR(vector x_raw, vector Q_r) {
    int N = num_elements(x_raw) + 1;
    vector [N] x;
    real x_aux = 0;

    for(i in 1:N-1){
      x[i] = x_aux + x_raw[i] * Q_r[i];
      x_aux = x_aux + x_raw[i] * Q_r[i+N];
    }
    x[N] = x_aux;
    return x;
  }
}

data {
  int<lower=0> N;
  int<lower=1> N_groups;
  int<lower=1,upper=N_groups> groups[N];
  int<lower=0> y[N];
}

transformed data {
  vector[2 * N_groups] groups_Q_r = Q_sum_to_zero_QR(N_groups);
}

parameters {
  real intercept;
  vector[N_groups - 1] group_r_raw; 
  real<lower=0> group_sd;
}

transformed parameters {
  vector[N_groups] group_r = sum_to_zero_QR(group_r_raw, groups_Q_r) * group_sd;
}

model {
  intercept ~ normal(5, 2);
  group_r_raw ~ normal(0, 1);
  group_sd ~ normal(0, 1);
  y ~ poisson_log(intercept + group_r[groups]);
}

"

model_nc_sz <- cmdstan_model(write_stan_file(model_code_nc_sz))
```
```{r}
fit_nc_sz <- model_nc_sz$sample(data = data_stan)
```
```{r}
fit_nc_sz$summary()
```

```{r}
mcmc_pairs(fit_nc_sz$draws(), pars = c("group_sd", "intercept"), regex_pars = "group_r_raw", np = nuts_params(fit_nc_sz),
           transformations = list("group_sd" = "log"))
```



