baseurl = "http://www.martinmodrak.cz/"
languageCode = "en-us"
title = "Martin Modrák"
theme = "hugo-tanka"
author = "Martin Modrák"
canonifyurls = true
languagecode = "en"
googleAnalytics = "UA-113619876-1"
disqusShortname = "martinmodrak"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$","\\.nb\\.html$"]

disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

[params]
  sitename = "Martin Modrák's Blog"


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "ORCID"
    url = "http://orcid.org/0000-0002-8886-7797"
    weight = 3 
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/martinmodrak"
    weight = 4
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/modrak_m"
    weight = 5

#[params]
#    description = "Software/Academia/Bioinformatics"

    # options for highlight.js (version, additional languages, and theme)
    #highlightjsVersion = "9.11.0"
    #highlightjsCDN = "//cdn.bootcss.com"
    #highlightjsLang = ["r", "yaml"]
    #highlightjsTheme = "github"

    #MathJaxCDN = "//cdn.bootcss.com"
    #MathJaxVersion = "2.7.1"
