baseurl = "/"
languageCode = "en-us"
title = "Martin Modrák"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "ORCID"
    url = "http://orcid.org/0000-0002-8886-7797"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/martinomdrak"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/modrak_m"

[params]
    description = "Software/Academia/Bioinformatics"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "portrait.jpg"
    width = 50
    height = 50
    alt = "That's me"

